name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            ninja_target_os: linux
#          - os: windows-latest
#            ninja_target_os: win
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4

    - name: Install Debian Dependencies
      if: runner.os == 'Linux'
      run: .github/scripts/install-debian-deps.sh

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: .github/scripts/install-macos-deps.sh

    - name: Install Windows Dependencies
      if: runner.os == 'Windows'
      run: .github\scripts\install-windows-deps.ps1

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build